### Day 4：Pandas

In [2]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in c:\Users\陳佩汶\Documents\Projects\my-first-python-tutorial\hello-world\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\陳佩汶\Documents\Projects\my-first-python-tutorial\hello-world\.venv\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\陳佩汶\Documents\Projects\my-first-python-tutorial\hello-world\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\陳佩汶\Documents\Projects\my-first-python-tutorial\hello-world\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\陳佩汶\Documents\Projects\my-first-python-tutorial\hello-world\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Part 1：建立 DataFrame ⭐

In [ ]:
#先建立dictionary
data = {
    "Name": ["Amy", "Bob", "Cindy"],
    "Age": [20, 25, 22],
    "Score": [90, 85, 95]
}

print(type(data))

#再轉成pd.DataFrame()
df = pd.DataFrame(data)

print(df)

<class 'dict'>
    Name  Age  Score
0    Amy   20     90
1    Bob   25     85
2  Cindy   22     95

In [8]:
print(df.columns)

print(df.shape)
#代表 3 筆資料（rows）3 個欄位（columns）

Index(['Name', 'Age', 'Score'], dtype='str')
(3, 3)

## Exercise 1 ⭐

In [5]:
data_2 = pd.DataFrame({
    "Name" : ["Tom", "Mary", "John"],
    "Age" : ["21", "23", "22"],
    "City" : ["Taipei", "Taichung", "Kaohsiung"]
})
print(data_2)

   Name Age       City
0   Tom  21     Taipei
1  Mary  23   Taichung
2  John  22  Kaohsiung

## Exercise 2 ⭐

In [6]:
df_3 = pd.DataFrame({
    "Product" : ["Apple", "Banana", "Orange"],
    "Price" : ["30", "20", "25"]
})


print(df_3)

  Product Price
0   Apple    30
1  Banana    20
2  Orange    25

### Part 2：讀取 CSV ⭐
Step 1：先安裝 seaborn

In [ ]:
!pip install seaborn

Step 2：載入 Titanic dataset

In [11]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

Step 3：查看前五筆資料

In [2]:
df.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## Exercise 3 ⭐
顯示前 3 筆資料：

In [3]:
df.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

## Exercise 4 ⭐
顯示前 8 筆資料。

In [4]:
df.head(8)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

## Exercise 5 ⭐
回答：

第一個欄位名稱？
最後一個欄位名稱？
一共有多少欄位？

In [7]:
print((f"第一個欄位名稱:{df.columns[0]}"))
print(f"最後一個欄位名稱:{df.columns[-1]}")
print(f"一共有{len(df.columns)}個欄位")

第一個欄位名稱:survived
最後一個欄位名稱:alone
一共有15個欄位

### Part 3：資料結構 ⭐⭐

In [15]:
print(df.shape)
print(len(df.columns))

(891, 15)
15

## Exercise 6 ⭐⭐

In [16]:
print(f"1. 有 {df.shape[0]} 筆資料")
print(f"2. 有 {df.shape[1]} 個欄位")

1. 有 891 筆資料
2. 有 15 個欄位

## Exercise 7 ⭐⭐

In [17]:
print(df.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

## Exercise 8 ⭐⭐

In [18]:
print(df.columns[0])
print(df.columns[-1])

survived
alone

## Part 4：info() 與 describe() ⭐⭐
學習

    df.info() 查看資料數量

    df.describe() 查看基本資料統計

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [13]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### Exercise 9 ⭐⭐
回答：

age 是否有缺失值？
sex 的資料型態？

In [14]:
# 1.df.info()顯示 age  714 non-null(未滿891個)
print("age 有缺失值")
# 2.df.describe()顯示 sex  891 non-null object
print("sex 的資料型態為object")

age 有缺失值
sex 的資料型態為object

In [15]:
print(f"1. age 有缺失值")
print(f"2. sex 的資料型態是 {df['sex'].dtype}")

1. age 有缺失值
2. sex 的資料型態是 str

### Exercise 10 ⭐⭐
回答：

平均年齡？
最大年齡？
最小年齡？

In [33]:
print(f"平均年齡:{df["age"].mean():.2f}歲")
print(f"最大年齡:{df["age"].max():.2f}歲")
print(f"最小年齡:{df["age"].min():.2f}歲")

#也可以先存成變數
age_mean = df["age"].mean()
print(age_mean)

平均年齡:29.70歲
最大年齡:80.00歲
最小年齡:0.42歲
29.69911764705882

## Part 5：Series（超重要）⭐⭐⭐

In [35]:
#取出一欄(column)
df["age"]
#查看型態
type(df["age"])

pandas.Series

### Exercise 11 ⭐⭐⭐

In [37]:
df["fare"]
type(df["fare"])

pandas.Series

### Exercise 12 ⭐⭐⭐

In [44]:
# 兩個中括號 [[]]得到Data frame
df[["sex", "class", "survived"]]
print(f"sex 的型態:{type(df["sex"])}")
print(f"class 的型態:{type(df["class"])}")
print(f"survived 的型態:{type(df["survived"])}")

sex 的型態:<class 'pandas.Series'>
class 的型態:<class 'pandas.Series'>
survived 的型態:<class 'pandas.Series'>

## Part 6：基本統計 ⭐⭐⭐

In [54]:
#平均值
age_mean = df["age"].mean()
print(f"平均值:{age_mean:.2f}")
#最大值
age_max = df["age"].max()
print(f"最大值:{age_max}")
#最小值
age_min = df["age"].min()
print(f"最小值:{age_min}")
#總和
fare_sum = df["fare"].sum()
print(f"總和:{fare_sum}")

平均值:29.70
最大值:80.0
最小值:0.42
總和:28693.9493

### Exercise 13 ⭐⭐⭐

找出：

平均票價。

In [56]:
fare_mean = df["fare"].mean()
print(f"平均票價:{fare_mean:.2f}")

平均票價:32.20

### Exercise 14 ⭐⭐⭐
找出：

最大票價
最小票價

In [60]:
#最大票價
fare_max = df["fare"].max()
print(f"最大票價:{fare_max:.2f}元")
#最小票價
fare_min = df["fare"].min()
print(f"最小票價:{fare_min:.2f}元")

最大票價:512.33元
最小票價:0.00元

## Part 7：loc ⭐⭐⭐
學習
    
    df.loc[0]

    df.loc[0, "age"]

    df.loc[0:4]

In [63]:
#找第 10 位乘客所有資料。
df.loc[9]

survived               1
pclass                 2
sex               female
age                 14.0
sibsp                  1
parch                  0
fare             30.0708
embarked               C
class             Second
who                child
adult_male         False
deck                 NaN
embark_town    Cherbourg
alive                yes
alone              False
Name: 9, dtype: object

In [64]:
#找第 20 位乘客的性別。
df.loc[19, "sex"]

'female'

In [69]:
#找第 50~52 位乘客性別及年齡。
df.loc[49:51, ["sex","age"]]

       sex   age
49  female  18.0
50    male   7.0
51    male  21.0

## Part 8：iloc ⭐⭐⭐
學習
   
    df.iloc[0]

    df.iloc[0,2]

    df.iloc[0:5]

In [71]:
#找第二列
df.iloc[3]

survived                 1
pclass                   1
sex                 female
age                   35.0
sibsp                    1
parch                    0
fare                  53.1
embarked                 S
class                First
who                  woman
adult_male           False
deck                     C
embark_town    Southampton
alive                  yes
alone                False
Name: 3, dtype: object

In [72]:
#找第十列第五欄
df.iloc[9, 4]

np.int64(1)

In [75]:
#找前二十列 [包含起始:不包含結尾]
df.iloc[0:20]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True

### Part 9：sort_values() ⭐⭐⭐
由小到大：

    df.sort_values("age")

由大到小：

    df.sort_values("age", ascending=False)

In [78]:
#找年齡最小的人.min()
df.loc[df["age"].idxmin()]

#🔥為什麼這樣寫？
#df["age"].min() → 只得到最小年齡（數字）
#idxmin() → 找到「最小值所在的 index」
#loc[] → 把那一整列資料抓出來

survived               1
pclass                 3
sex                 male
age                 0.42
sibsp                  0
parch                  1
fare              8.5167
embarked               C
class              Third
who                child
adult_male         False
deck                 NaN
embark_town    Cherbourg
alive                yes
alone              False
Name: 803, dtype: object

In [79]:
# .head()從頭開始選
df.sort_values("age").head(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False

In [84]:
# 找年齡最大的前五人
df.sort_values("age", ascending = False).head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

### 「找最大前幾名 = 排序 + [["column"]] + head()

In [87]:
df.sort_values("age", ascending=False)[["age"]].head(5)

      age
630  80.0
851  74.0
493  71.0
96   71.0
116  70.5

In [89]:
#找票價最高的人
df.sort_values("fare", ascending = False)[["fare"]].head(1)

         fare
679  512.3292

### Part 10：value_counts() ⭐⭐⭐
df["sex"].value_counts()

In [92]:
#統計：男性與女性的人數
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [103]:
#哪個艙等最多？
df["class"].value_counts().head(1)

class
Third    491
Name: count, dtype: int64

👉 想要「最多的是誰」→ idxmax()

👉 想要「最多+數量」→ value_counts().head(1)

In [105]:
df["class"].value_counts().idxmax()

'Third'

In [106]:
#生還多少人？死亡多少人？
df["survived"].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

### 🔥 如果老師要你「清楚標示」

### ✔ 方法 1：改 index 名稱

In [107]:
df["survived"].value_counts().rename(index={0: "Dead", 1: "Survived"})

survived
Dead        549
Survived    342
Name: count, dtype: int64

### ✔ 方法 2：轉成字典（很清楚）

In [108]:
df["survived"].value_counts().to_dict()

{0: 549, 1: 342}

### ✔ 方法 3：分開寫（最直觀）

In [109]:
print("生還人數:", (df["survived"] == 1).sum())
print("死亡人數:", (df["survived"] == 0).sum())

生還人數: 342
死亡人數: 549

### Project 1：Titanic Dataset Overview ⭐

完成：

載入資料

查看前五筆

查看資料資訊

查看統計量

In [113]:
import pandas as pd
import seaborn as sns
#載入資料
df = sns.load_dataset("titanic")

In [112]:
#查看前五筆
df.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
#查看資料資訊👉 info() = 看資料「骨架」
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [ ]:
#查看統計量👉 幫你快速算出「數值欄位的統計摘要」
df.describe(include="all") #會連文字欄位一起統計

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Project 2：Passenger Search ⭐⭐
找出：

第 0 位乘客
第 10 位乘客
第 100 位乘客

df.loc[第幾位就輸入幾]

In [119]:
#第0位客人
df.loc[0]

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

In [126]:
#第10位客人
df.loc[10]

survived                 1
pclass                   3
sex                 female
age                    4.0
sibsp                    1
parch                    1
fare                  16.7
embarked                 S
class                Third
who                  child
adult_male           False
deck                     G
embark_town    Southampton
alive                  yes
alone                False
Name: 10, dtype: object

In [127]:
#第100位客人
df.loc[100]

survived                 0
pclass                   3
sex                 female
age                   28.0
sibsp                    0
parch                    0
fare                7.8958
embarked                 S
class                Third
who                  woman
adult_male           False
deck                   NaN
embark_town    Southampton
alive                   no
alone                 True
Name: 100, dtype: object

### Project 3：loc 練習 ⭐⭐
找出：

第 5 位乘客年齡
第 30 位乘客性別
第 50 位乘客是否生存

In [129]:
#第5位乘客年齡
df.loc[5, ["age"]]

age   NaN
Name: 5, dtype: float64

In [130]:
#第30位乘客性別
df.loc[30, ["sex"]]

sex    male
Name: 30, dtype: str

In [135]:
#第 50 位乘客是否生存
df.loc[50, ["survived"]]

survived    0
Name: 50, dtype: int64

### Project 4：iloc 練習 ⭐⭐
找出：

第一列第三欄
第十列第五欄
前二十列

In [16]:
#第一列第三欄
df.iloc[0,2]

'male'

In [17]:
#第十列第五欄
df.iloc[9,4]

np.int64(1)

In [138]:
#前二十列
df.iloc[0:20]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True

### Project 5：排序分析 ⭐⭐⭐
找出：

年齡最小的人
年齡最大的人
票價最高的人

In [19]:
#找出年齡最小的人
df.sort_values("age").head(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False

In [20]:
#只顯示"人"和"年齡"
print(df["age"].idxmin()) 
print(df["age"].min())

803
0.42

In [143]:
#年齡最大的人
df.sort_values("age", ascending = False).head(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0,S,First,man,True,A,Southampton,yes,True

In [23]:
print(df["age"].idxmax())
print(df["age"].max())

630
80.0

In [40]:
#票價最高的人
df.sort_values("fare", ascending = False).head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True

In [ ]:
#結果發現票價最高的不只一個人
print(df["fare"].max())

print(list(df[df["fare"] == df["fare"].max()].index))

len(df[df["fare"] == df["fare"].max()])

512.3292
[258, 679, 737]

3

### Project 6：男女比例分析 ⭐⭐⭐
男性有幾位？
女性有幾位？
哪個性別較多？

In [145]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

### Project 7：艙等分析 ⭐⭐⭐
哪個艙等最多？

In [42]:
df["class"].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

### Project 8：年齡 Top10 ⭐⭐⭐⭐
找出：

年齡最大的前 10 人

In [147]:
df.sort_values("age", ascending= False).head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
745,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
672,0,2,male,70.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
456,0,1,male,65.0,0,0,26.5500,S,First,man,True,E,Southampton,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False

### Project 9：生還率分析 ⭐⭐⭐⭐
統計：

生還人數
死亡人數
並計算：

生還率 = 生還人數 ÷ 總人數 × 100%

In [ ]:
df["survived"].value_counts().rename(index={0 :"Dead", 1 : "Survive"})

生還率 = 342/(549+342)*100 #等於平均值(不要把數字寫死)
print(生還率,"%")

38.38383838383838 %

In [ ]:
#正確版
生還率 = df["survived"].mean()*100
print(f"{生還率:.2f}%")

38.38%

### Project 10：Data Scientist Mini Report ⭐⭐⭐⭐⭐

### 1.Titanic 有多少筆資料？

In [164]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

### 2.有多少欄位？

In [167]:
print(len(df.columns))

15

### 3.平均年齡是多少？

In [170]:
age_mean = df["age"].mean()
print(f"平均年齡:{age_mean:.2f}")

平均年齡:29.70

### 4.平均票價是多少？

In [172]:
fare_mean = df["fare"].mean()
print(f"平均票價:{fare_mean:.2f}元")

平均票價:32.20元

### 5.男女人數？

In [173]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

### 6.哪個艙等最多？

In [174]:
df["class"].value_counts().head(1)

class
Third    491
Name: count, dtype: int64

## Bonus（Day 4+）⭐⭐⭐⭐⭐

In [175]:
#Boolean Indexing
df[df["sex"] == "female"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [ ]:
print(f"女性總共有{(df["sex"] == "female").sum()}人")

女性總共有314人

In [176]:
df[df["age"] > 60]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
170,0,1,male,61.0,0,0,33.5000,S,First,man,True,B,Southampton,no,True
252,0,1,male,62.0,0,0,26.5500,S,First,man,True,C,Southampton,no,True
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
280,0,3,male,65.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
326,0,3,male,61.0,0,0,6.2375,S,Third,man,True,NaN,Southampton,no,True
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
456,0,1,male,65.0,0,0,26.5500,S,First,man,True,E,Southampton,no,True
483,1,3,female,63.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,yes,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
545,0,1,male,64.0,0,0,26.0000,S,First,man,True,NaN,Southampton,no,True
555,0,1,male,62.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True
570,1,2,male,62.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,yes,True
625,0,1,male,61.0,0,0,32.3208,S,First,man,True,D,Southampton,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
672,0,2,male,70.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
745,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [56]:
print(f"大於60歲總共有{(df["age"] > 60).sum()}人")

大於60歲總共有22人

In [177]:
df[df["fare"] > 100]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
118,0,1,male,24.00,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
195,1,1,female,58.00,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
258,1,1,female,35.00,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
268,1,1,female,58.00,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.00,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
299,1,1,female,50.00,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.00,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.00,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.00,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
332,0,1,male,38.00,0,1,153.4625,S,First,man,True,C,Southampton,no,False
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
337,1,1,female,41.00,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
373,0,1,male,22.00,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
377,0,1,male,27.00,0,2,211.5000,C,First,man,True,C,Cherbourg,no,False
380,1,1,female,42.00,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
393,1,1,female,23.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
438,0,1,male,64.00,1,4,263.0000,S,First,man,True,C,Southampton,no,False
498,0,1,female,25.00,1,2,151.5500,S,First,woman,False,C,Southampton,no,False
505,0,1,male,18.00,1,0,108.9000,C,First,man,True,C,Cherbourg,no,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
537,1,1,female,30.00,0,0,106.4250,C,First,woman,False,NaN,Cherbourg,yes,True
544,0,1,male,50.00,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True
581,1,1,female,39.00,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
609,1,1,female,40.00,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
659,0,1,male,58.00,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
660,1,1,male,50.00,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
679,1,1,male,36.00,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
698,0,1,male,49.00,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
708,1,1,female,22.00,0,0,151.5500,S,First,woman,False,NaN,Southampton,yes,True
716,1,1,female,38.00,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
730,1,1,female,29.00,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
737,1,1,male,35.00,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
763,1,1,female,36.00,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
779,1,1,female,43.00,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
856,1,1,female,45.00,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False

In [57]:
print(f"票價大於100總共有{(df["fare"]>100).sum()}人")

票價大於100總共有53人

In [58]:
import pandas as pd

df =  pd.DataFrame({
    "Apple" : [2, 5, 6],
    "Orange" : [3, 4, 10],
    "Banana" : [6, 9 ,4]
})


print(df)

   Apple  Orange  Banana
0      2       3       6
1      5       4       9
2      6      10       4

iloc遵循 Python slicing 規則：

list[開始:結束]

輸出不包含結束列

In [62]:
df.iloc[0:2]

   Apple  Orange  Banana
0      2       3       6
1      5       4       9

loc

Pandas 設計者覺得：

用標籤(label)切片時，包含結尾比較直覺

所以：

df.loc[0:2]

會取：

0
1
2

In [61]:
df.loc[0:2]

   Apple  Orange  Banana
0      2       3       6
1      5       4       9
2      6      10       4

| 功能              | loc       | iloc         |
| --------------- | --------- | ------------ |
| 用什麼取值           | 標籤(label) | 位置(position) |
| 取單一列 (第二列)     | `loc[3]`  | `iloc[3]`    |
| 切片是否包含結尾        | ✅ 包含      | ❌ 不包含        |
| 遵守 Python slice | ❌         | ✅            |